spring:
  application:
    name: quiz-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: quiz-service, keycloak
  servlet:
    multipart:
      enabled: true
      maxFileSize: 10MB
      maxRequestSize: 10MB