server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: question-service
          uri: lb://QUESTION-SERVICE
          predicates:
            - Path=/questions/**
        - id: quiz-service
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/quizzes/**